#!/bin/sh
code --install-extension aaron-bond.better-comments
code --install-extension akamud.vscode-theme-onedark
code --install-extension anseki.vscode-color
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension aykutsarac.jsoncrack-vscode
code --install-extension azemoh.one-monokai
code --install-extension bbenoist.nix
code --install-extension beardedbear.beardedtheme
code --install-extension bierner.markdown-mermaid
code --install-extension chrisdias.vscode-opennewinstance
code --install-extension christian-kohler.npm-intellisense
code --install-extension codezombiech.gitignore
code --install-extension cweijan.dbclient-jdbc
code --install-extension cweijan.vscode-database-client2
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-environment-manager
code --install-extension dracula-theme.theme-dracula
code --install-extension editorconfig.editorconfig
code --install-extension eliverlara.andromeda
code --install-extension enkia.tokyo-night
code --install-extension equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension geeebe.duplicate
code --install-extension github.github-vscode-theme
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension gruntfuggly.todo-tree
code --install-extension jdinhlife.gruvbox
code --install-extension jock.svg
code --install-extension johnpapa.vscode-peacock
code --install-extension kevinrose.vsc-python-indent
code --install-extension leonardssh.vscord
code --install-extension liuchao.go-struct-tag
code --install-extension mechatroner.rainbow-csv
code --install-extension mgesbert.python-path
code --install-extension mhutchie.git-graph
code --install-extension michelemelluso.gitignore
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension napthedevhcj.atom-background-modified
code --install-extension njpwerner.autodocstring
code --install-extension njqdev.vscode-python-typehint
code --install-extension pkief.material-icon-theme
code --install-extension postman.postman-for-vscode
code --install-extension randomfractalsinc.snippets-viewer
code --install-extension redhat.vscode-yaml
code --install-extension samuelepignone.fakedonalds
code --install-extension sourcegraph.cody-ai
code --install-extension sveggiani.vscode-field-lights
code --install-extension syler.sass-indented
code --install-extension tinkertrain.theme-panda
code --install-extension uctakeoff.vscode-counter
code --install-extension usernamehw.errorlens
code --install-extension vinliao.fast-arrow
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension wakatime.vscode-wakatime
code --install-extension whizkydee.material-palenight-theme
code --install-extension wix.vscode-import-cost
code --install-extension yzhang.markdown-all-in-one
code --install-extension zainchen.json
code --install-extension zguolee.tabler-icons
